DROP DATABASE IF EXISTS twiter;
CREATE DATABASE twiter;
USE twiter;

CREATE TABLE users(
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    bird_date DATE NOT NULL
);